# Hamburg Points of Interest - Sample Notebook

## Explore data

In [1]:

import pandas as pd        

# Read csv file
dataframe = pd.read_csv("./data/03-gold/hamburg-points-of-interest-2026-04-csv/hamburg-points-of-interest-universities-quarter.csv")

In [2]:

# Display 5 first rows
dataframe.head()

        id  points_of_interest
0  1101102                   1
1  1102103                   2
2  1103108                   4
3  1106115                   1
4  2201204                   1

In [3]:

# Display dataframe info
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  10 non-null     int64
 1   points_of_interest  10 non-null     int64
dtypes: int64(2)
memory usage: 292.0 bytes

In [4]:

# Describe dataframe
dataframe.describe()

                 id  points_of_interest
count  1.000000e+01             10.0000
mean   3.083690e+06              2.9000
std    2.248989e+06              3.3483
min    1.101102e+06              1.0000
25%    1.103860e+06              1.0000
50%    2.751758e+06              2.0000
75%    4.133398e+06              2.7500
max    7.701701e+06             12.0000